service: notifications

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: ${opt:stage, 'local'}

custom:
  localstack:
    stages:
      - local
    autostart: true

resources:
  Resources:
    ArtifactChanges:
      Type: AWS::SNS::Topic

  Outputs:
    ArtifactChanges:
      Value: !Ref ArtifactChanges